name: lstm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _tflow_select
  - absl-py
  - argcomplete
  - astunparse
  - blas
  - blinker
  - brotlipy
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - click
  - cryptography
  - cycler
  - dbus
  - expat
  - fontconfig
  - freetype
  - gast
  - glib
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - idna
  - importlib_metadata
  - intel-openmp
  - joblib
  - jpeg
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - llvmlite
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numba
  - numpy
  - numpy-base
  - oauthlib
  - openssl
  - opt_einsum
  - pandas
  - pcre
  - pip
  - protobuf
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pyts
  - pytz
  - pyyaml
  - qt
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tbb
  - tensorboard
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - tk
  - tornado
  - urllib3
  - werkzeug
  - wheel
  - wrapt
  - xz
  - yaml
  - zipp
  - zlib

